// <auto-generated />
using Demo.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20250311093526_MigrationName")]
    partial class MigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("Demo.Models.BlackjackUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DealerValue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameResult")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerValue")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("blackjack");
                });

            modelBuilder.Entity("Demo.Models.GuessTheNumberUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("guessTheNumber");
                });
#pragma warning restore 612, 618
        }
    }
}
